### ISSUE TITLE
Activated toolbox for colour control blocks other controls

### ISSUE THREAD

**Issue by stweil** [slub/dfg-viewer#109]
As soon as the toolbox for contrast, colour and more is activated (button at right top), all other top controls with the exception of full screen no longer work. Selecting the toolbox button again does not deactivate the toolbox. Tested with Firefox on Windows and Linux on http://dfg-viewer.de/ demonstrator.

[One of the demonstrator images](http://dfg-viewer.de/show/?tx_dlf%5Bid%5D=http%3A%2F%2Fdaten.digitale-sammlungen.de%2F~db%2Fmets%2Fbsb00020619_mets.xml) neither shows the toolbox button nor any thumbnail images.

**Comment by albig** [comment]
Thank you for reporting. The blocking image manipulation tool has been fixed in #110 .

The mentioned demonstrator images lacks the support of CORS. That's why WebGL is disabled and the image manipulation tool cannot work.

**Comment by stweil** [comment]
That was a really fast response and fix, many thanks. I can confirm that it works now as expected.
