### ISSUE TITLE
mehrere DMDIDs in <structmap TYPE="LOGICAL"><div>...

### ISSUE THREAD

**Issue by jbarth-ubhd** [slub/dfg-viewer#118]
Gibt es zu einem `<div>` innerhalb von `<structMap TYPE="LOGICAL">` mehrere `<dmdSec>`, sind deren `ID` beim `<div>` als Attribut `DMDID="id1 id2 id3 ..."` (mit Leerzeichen getrennt) anzugeben.

Dann zeigt der DFG-Viewer jedoch links oben keine Metadaten an, vermutlich weil der String in `DMDID` als ganzes gesucht wird.
Die Suche nach der richtigen `<dmdSec>` anhand der einzelnen `ID` müsste dann auch die Einschränkung auf `dmdSec/mdWrap[@MDTYPE="MODS"]` beinhalten.

**Comment by jbarth-ubhd** [comment]
Ist der Demonstrator bereits v3? Die Metadaten erscheinen leider noch nicht...

**Comment by sebastian-meyer** [comment]
Das muss im zugrundeliegenden Kitodo.Presentation behoben werden. Ich habe dort ein entsprechendes Issue aufgemacht und schaue es mir gleich an: https://github.com/kitodo/kitodo-presentation/issues/417

**Comment by sebastian-meyer** [comment]
Die Unterstützung für multiple DMDIDs wurde in Kitodo.Presentation implementiert und ist jetzt auch für den DFG-Viewer aktiv.
