### ISSUE TITLE
Darstellungsproblem im IE 11

### ISSUE THREAD

**Issue by olivergoetze** [slub/dfg-viewer#173]
Im Internet Explorer 11 werden Digitalisate nicht mehr angezeigt.

Der Bereich zur Anzeige des Digitalisats bleibt weiß.
Beispiel: 
http://dfg-viewer.de/show/?tx_dlf[id]=https%3A%2F%2Fwww.landesarchiv-bw.de%2Fdfgviewer%2Fmods1-1263080.xml

![image](https://user-images.githubusercontent.com/7281525/98952077-510b0500-24fb-11eb-8768-791ac9e6fb4e.png)

Getestet in Internet Explorer 11.1518.17763.0 unter Windows 10 1809.
In Chrome, Firefox und Edge scheint dieses Problem nicht aufzutreten.

**Comment by albig** [comment]
This is related to https://github.com/kitodo/kitodo-presentation/issues/544

**Comment by albig** [comment]
Microsoft has announced end of IE11 now: https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

**Comment by albig** [comment]
The current notification for IE11 users is bad for older Firefox versions like 52 esr.

![hinweis-dfg-viewer](https://user-images.githubusercontent.com/3354500/111458131-5aaab080-8719-11eb-9149-304612b8d864.png)

- The JavaScript ECMAScript detection fails and the notfification is shown
- All JavaScript of the DFG-Viewer / Kitodo.Presentation is working nevertheless

So this approach to inform the user about an outdated browser is not yet optimal.
