### ISSUE TITLE
Signatur in der Anzeige

### ISSUE THREAD

**Issue by StephanMa** [slub/dfg-viewer#177]
Wäre es möglich, die Signatur noch im DFG Viewer mit unterzubekommen? Derzeit würden wir die Signatur als String an den Titel anfügen, was irgendwie auch nicht Sinn der Sache ist.

**Comment by sebastian-meyer** [comment]
Die Signatur wird im DFG-Viewer bereits angezeigt. Die Kodierung dafür ist:

MODS: `./mods:location/mods:shelfLocator`

TEIHDR: `./teihdr:fileDesc/teihdr:sourceDesc/teihdr:msDesc/teihdr:msIdentifier/teihdr:idno`

**Comment by StephanMa** [comment]
Ich bin verwirrt... war das ursprünglich nicht mal identifier? 
ok dann füllen wir das Feld auch mit.
Danke

**Comment by sebastian-meyer** [comment]
Soweit ich mich erinnern kann, hat sich die Kodierung nicht geändert. 🤔
