### ISSUE TITLE
aggregatorLogo/sponsorLogo

### ISSUE THREAD

**Issue by avielhauer-ub** [slub/dfg-viewer#178]
Die Logos unter <dv:aggregatorLogo> und <dv:sponsorLogo> werden aktuell im Viewer nicht angezeigt.

**Comment by albig** [comment]
Das ist ein Bug, da im [METS-Anwendungsprofil 2.3.1](http://dfg-viewer.de/fileadmin/groups/dfgviewer/METS-Anwendungsprofil_2.3.1.pdf) im Abschnitt 2.7.2.5 bis 2.7.2.10 beschrieben ist, dass diese Logos angezeigt werden.
