### ISSUE TITLE
Two finger zoom is not working properly

### ISSUE THREAD

**Issue by albig** [slub/dfg-viewer#201]
Via Mailing-List:

> 
> Im DFG-Viewer soll man ja wohl auch mit der 2-Finger-Geste zoomen können. Das geht bei mir /Mac, alle Browser/ zu rasch. Es ist kaum kontrollierbar und damit leider nahezu unbenutzbar. Ist das eine Mac-Eigenart oder liegt das Problem woanders?
> 
> Beispiele:
> https://sachsen.digital/werkansicht?tx_dlf[id]=3632&tx_dlf[page]=1
> http://dfg-viewer.de/show/?tx_dlf[id]=http://mets.sub.uni-hamburg.de/kitodo/PPN611986183

**Comment by albig** [comment]
Related to Kitodo.Presentation. Maybe already enhanced/fixed by https://github.com/kitodo/kitodo-presentation/pull/763 @dvoracek-slub?

**Comment by dvoracek-slub** [comment]
Haven't tried this on a Mac, but yes, I think this should be fixed by the OL upgrade. You can observe that behavior on a PC laptop as well when using the scrolling gesture for zooming.

[In the release notes](https://github.com/openlayers/openlayers/blob/main/changelog/v3.20.0.md), they say:

> On the subject of view transitions, scrolling with a trackpad or magic mouse now transitions the view resolution smoothly. Instead of jumping to the next integer zoom level, trackpad or magic mouse scrolling can leave the view at a fractional zoom level. In line with this trackpad behavior, pinch zooming on touch devices also now leaves the view at a fractional zoom level (see the upgrade notes for an option to restore the old behavior).
