### ISSUE TITLE
Tag new release 6.0

### ISSUE THREAD

**Issue by stweil** [slub/dfg-viewer#211]
While the documentation already refers to release 6.0, there is currently no such tag. The latest release which is shown on GitHub is still 5.3.

**Comment by csidirop** [comment]
In addition, you should also update the[ TYPO3 repo](https://extensions.typo3.org/extension/dfgviewer/) so that it can be easily installed via composer.

**Comment by csidirop** [comment]
@sebastian-meyer Anything new here? 

With commit https://github.com/slub/dfg-viewer/commit/367992ebd4084009fe04f2dc4c04856618c3a6f3 end of july 22 you bumped the version. What is missing for an official version 6?
