### ISSUE TITLE
Support TYPO3 v11

### ISSUE THREAD

**Issue by csidirop** [slub/dfg-viewer#239]
Now that[ .presentation got support for TYPO3 v11](https://github.com/kitodo/kitodo-presentation/pull/885#issuecomment-1721573897) we need that support for the dfg-viewer (and your [slub_digitalcollections](https://github.com/slub/slub_digitalcollections)).

I have tried a bit, it could be that the dfgviewer will work without major changes. It seams that the bare viewer is shown correctly: 
![grafik](https://github.com/slub/dfg-viewer/assets/43964592/eb857b05-058f-4273-92e4-5354f75ff4d3)

But trying to show a document throws an exception: 
```
503
Oops, an error occurred!
```

`Class 'TYPO3\CMS\Frontend\Page\PageRepository' not found | Error thrown in file /var/www/typo3/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3218`

Although I must admit I'm not sure if the problem isn't in .presentation after all. Because I could not test if the presentation viewer could show any documents.

**Comment by beatrycze-volk** [comment]
I have made small tests by myself and it looks that this problem is already solved in Kitodo.Presentation so feel free to make PR with your changes.

**Comment by csidirop** [comment]
I've redone my tests, and it looks very good. 

There are a few steps needed:
- DFG-Viewer: Set cms-core to ^11
- slub-digitalcollections: Set cms-core to ^11
- After setting TYPO3 up and installing the extensions via composer, the default pages where not shown. I had to do a `vendor/bin/typo3cms extension:setup` and then create a new page. This way the default page setup was shown again.

I've tested most of what I'm using, and everything worked. I did not test the 3D-Viewer (an instruction is still warmly welcomed). I may do some more tests tomorrow. 

System: 
- TYPO3 v11.5.34-dev
- PHP 7.4.1

For an easy setup you can use my docker: https://github.com/csidirop/kitodo-presentation-docker/tree/typo3v11-test
