### ISSUE TITLE
License conditions

### ISSUE THREAD

**Issue by stweil** [slub/dfg-viewer#31]
http://dfg-viewer.de/en/regarding-the-project/was-ist-der-dfg-viewer/  and http://dfg-viewer.de/en/regarding-the-project/conditions-of-use/ both say that the code may be used according to GPL 3.

https://github.com/slub/dfg-viewer/blob/master/dfgviewer/LICENSE.txt is a copy of the GPL 2. Should it be replaced by the GPL 3 text?

http://dfg-viewer.de/en/imprint/ says that several elements are protected under copyright. How does this match with GPL 2 or GPL 3? Would it be legally possible to create a public docker container based on slub/dfg-viewer and kitodo/kitodo-presentation without the conditions required by http://dfg-viewer.de/en/regarding-the-project/conditions-of-use/?

**Comment by akuckartz** [comment]
:+1:

**Comment by stweil** [comment]
Link updates:
http://dfg-viewer.de/en/das-projekt/was-ist-der-dfg-viewer
http://dfg-viewer.de/en/the-project/conditions-of-use
https://github.com/slub/dfg-viewer/blob/master/LICENSE.txt

**Comment by beatrycze-volk** [comment]
The license was updated (thank you @stweil!), so I close this ticket.
