### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by stweil** [slub/dfg-viewer#33]
The latest released version (TYPO3 extension) is not compatible with the latest released version of Kitodo.Presentation (missing helper functions, maybe more problems). Therefore a new released version would be appreciated.

The current Git master version does not show page images (see my comment to PR #29), so before creating a release, more work is needed. In my tests, I also see neither author nor title from the meta data. Instead of that information, only `[]` is shown.

**Comment by albig** [comment]
In the meanwhile a release 4.0.1 has been published to fullfill this requirement: https://github.com/slub/dfg-viewer/releases/tag/v4.0.1

Current release will work with TYPO3 7.6. Support of TYPO3 8.7 depends on Kitodo.Presentation.
