### ISSUE TITLE
Hervorhebung des Inhalts

### ISSUE THREAD

**Issue by philipphegel** [slub/dfg-viewer#69]
Meines Erachtens wäre es noch schön, wenn der Inhalt, in dem man sich gerade befindet, im Inhaltsverzeichnis hervorgehoben werden kann. Die alte Version tat das.

**Comment by philipphegel** [comment]
Bei Inhalten in Inhalten wie [hier](http://dfg-viewer.de/show/?tx_dlf%5Bpage%5D=99&tx_dlf%5Bid%5D=http%3A%2F%2Fzimks68.uni-trier.de%2Fstmatthias%2FT1267%2FT1267-digitalisat.xml&tx_dlf%5Bdouble%5D=0&cHash=7bde4cc6cd040ee9192eb588ee46c701) funktioniert es übrigens jetzt schon.

**Comment by philipphegel** [comment]
In diesem Zusammenhang ist vielleicht noch interessant, dass [sehr lange Titel für Abschnitte](http://dfg-viewer.de/show/?set[mets]=http%3A%2F%2Fzimks68.uni-trier.de%2Fstmatthias%2FT1376%2FT1376-digitalisat.xml), wenn ich es richtig sehe, nie komplett angezeigt werden. Ich weiß nicht, ob es dafür eine wirklich elegante Lösung gibt und etwa "hängend" umgebrochen werden sollte.

**Comment by albig** [comment]
Die langen Titel werden abgeschnitten, aber beim Hoven mit der Maus werden sie vollständig angezeigt.

Die Highlighten der aktuellen Position im Inhaltsverzeichnis (1. Ebene) müsste sich bitte mal @gnuj  anschauen.
