### ISSUE TITLE
<dv:presentation>

### ISSUE THREAD

**Issue by philipphegel** [slub/dfg-viewer#74]
Wir haben in unseren, etwas älteren Daten, Links auf Präsentationen so angegeben:

```
<mets:digiprovMD ID="T0152-DIGIPROVAMD">
 <mets:mdWrap MDTYPE="OTHER" MIMETYPE="text/xml" OTHERMDTYPE="DVLINKS">
  <mets:xmlData>
   <dv:reference>http://zimks68.uni-trier.de/stmatthias/T0152/T0152-digitalisat.xml</dv:reference>                        
   <dv:presentation>http://www.stmatthias.uni-trier.de/</dv:presentation>
  </mets:xmlData>
 </mets:mdWrap>
</mets:digiprovMD>
```

Das ist aber veraltet und sollte nun wohl eigentlich in einem <dv:links> stehen. Die Frage ist, ob diese alte Schreibweise nicht auch noch unterstützt werden sollte. Falls diese Art der Angabe nie unterstützt wurde, erübrigt sich die Frage natürlich und wir sollten unsere Daten noch einmal überarbeiten.

**Comment by sebastian-meyer** [comment]
Wenn ich mich recht erinnere, war das `dv:links` schon immer verpflichtend. Zumindest habe ich in keiner mir noch vorliegenden älteren Fassung etwas anderes gefunden.

**Comment by philipphegel** [comment]
Sie haben ganz recht.  Das war schon immer falsch:

https://maillist.slub-dresden.de/pipermail/dv-technik/2015-July/000847.html

Das Skript, um das zu korrigieren, habe ich nun endlich geschrieben. Da war wohl etwas durcheinander geraten. Das Ticket kann jedenfalls geschlossen werden. Vielen Dank für den Hinweis.
