### ISSUE TITLE
Hide Link to local presentation if not set

### ISSUE THREAD

**Issue by albig** [slub/dfg-viewer#82]
Example: http://dfg-viewer.de/show/?tx_dlf%5Bid%5D=http%3A%2F%2Fwww.landesarchiv-nrw.de%2Fdigitalisate%2FAbt_Westfalen%2FGrafschaft_Mark_Gerichte_III%2F00005_01%2Fmets.xml

**Comment by albig** [comment]
Question to @gnuj : should we hide this link or should we just disable this link by a span-tag. I prefer last idea with a <span class="local-presentation">, but this needs some changes in CSS.

**Comment by gnuj** [comment]
Solved with latest merge request #85.
