### ISSUE TITLE
Wrong link to year in calendar chart

### ISSUE THREAD

**Issue by KnutLohse** [slub/dfg-viewer#83]
Calender chart (display content of mets_year.xml):
Link to the year above the calendar chart is missleading (document 1 instead of address of mets_year.xml).
Same target in left sidebar is correct.

**Comment by albig** [comment]
This is an example: http://dfg-viewer.de/show/?tx_dlf%5Bid%5D=http%3A%2F%2Fdigital.slub-dresden.de%2Ffileadmin%2Fdata%2F399196951-18290922%2F399196951-18290922_year.xml
